import type { Metadata } from "next";
import { Cabin, Geist, Geist_Mono, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const cabin = Cabin({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-cabin",
});

const trebuchetFont = localFont({
  src: "./fonts/trebuc.ttf",
});

export const metadata: Metadata = {
  title: "Casspr Super",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${trebuchetFont.className} antialiased `}
        suppressHydrationWarning={true}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
