import { CampaignData } from "@/types/calender";


export const campaignData: CampaignData = {
  campaign_strategy: {
    creative_direction: "Empower Your Fitness Journey with PUMA",
    primary_pillars: ["Educational", "Inspirational", "Community"],
    viral_elements: ["Social Proof", "FOMO"],
    differentiation: "Automatic Discounts for Effortless Savings",
    campaign_arc:
      "Building brand awareness through education and community engagement, culminating in exclusive product showcases.",
  },
  campaign_timeline: {
    duration_weeks: 4, 
    start_date: "2025-09-22",
    end_date: "2025-10-20",
    total_posts: 28,
    posts_per_week: 7,
    posting_days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    weekly_themes: [
      "Kickstart Your Fitness Journey",
      "Community Connection",
      "Inspiration and Motivation",
      "Celebrate Style and Performance",
    ],
  },
  content_calendar: [
    {
      post_number: 1,
      date: "2025-09-22",
      day_of_week: "Monday",
      week_number: 1,
      platform: "Instagram",
      content_pillar: "Educational",
      funnel_stage: "AWARENESS",
      content_concept: {
        concept_id: "EDU_001",
        title: "Athletic Shoe Buying Guide",
        description:
          "A carousel post providing tips on choosing the right athletic shoes.",
        hook: "Don't just buy shoes, buy the right ones!",
        value_proposition: "Learn how to enhance your performance.",
        call_to_action: "Swipe to learn more!",
        engagement_tactics: ["Polls on stories", "Comment prompts"],
      },
      creative_elements: {
        format: "CAROUSEL",
        visual_concept:
          "Bright, engaging graphics with shoe recommendations.",
        copy_angle: "Empower your performance with the right shoes.",
        hashtag_strategy: ["#PUMA", "#AthleticShoes", "#FitnessTips"],
        viral_triggers: ["Knowledge is power"],
      },
      strategic_context: {
        week_focus: "Kickstart Your Fitness Journey",
        psychological_principle: "Knowledge is power",
        expected_engagement: "High interaction through comments and shares",
        success_metrics: ["Engagement Rates", "Shares", "Comments"],
        optimization_notes: "Boost post for wider reach.",
      },
      production_requirements: {
        effort_level: "MEDIUM",
        resources_needed: ["Graphic designer", "Content writer"],
        preparation_time: "2 days",
        collaboration_needs: "Marketing team for insights",
      },
    },
    {
      post_number: 2,
      date: "2025-09-23",
      day_of_week: "Tuesday",
      week_number: 1,
      platform: "Facebook",
      content_pillar: "Behind-the-Scenes",
      funnel_stage: "CONSIDERATION",
      content_concept: {
        concept_id: "BTS_001",
        title: "Our Design Process",
        description:
          "Behind-the-scenes look at how our products are designed.",
        hook: "Ever wondered how your favorite shoes are made?",
        value_proposition: "Transparency builds trust.",
        call_to_action: "Learn more about our process!",
        engagement_tactics: ["Q&A about design choices"],
      },
      creative_elements: {
        format: "VIDEO",
        visual_concept: "Documentary-style video featuring design stages.",
        copy_angle:
          "Discover the artistry behind your favorite PUMA products.",
        hashtag_strategy: ["#BehindTheScenes", "#PUMADesign"],
        viral_triggers: ["Curiosity about brand processes"],
      },
      strategic_context: {
        week_focus: "Kickstart Your Fitness Journey",
        psychological_principle: "Connection to the brand",
        expected_engagement: "Increased video views and shares",
        success_metrics: ["Video Views", "Comments"],
        optimization_notes: "Post at peak engagement times.",
      },
      production_requirements: {
        effort_level: "HIGH",
        resources_needed: ["Videographer", "Editor"],
        preparation_time: "4 days",
        collaboration_needs: "Design team for insights",
      },
    },
    {
        post_number: 3,
        date: "2025-09-24",
        day_of_week: "Wednesday",
        week_number: 1,
        platform: "YouTube",
        content_pillar: "Educational",
        funnel_stage: "AWARENESS",
        content_concept: {
          concept_id: "EDU_002",
          title: "Fashion Meets Function",
          description:
            "Video showcasing the performance benefits of the latest sneaker releases.",
          hook: "Why choose between style and performance?",
          value_proposition:
            "Discover your perfect shoe for both gym and street.",
          call_to_action: "Watch now and find your fit!",
          engagement_tactics: [
            "Challenge viewers to comment their favorite looks",
          ],
        },
        creative_elements: {
          format: "VIDEO",
          visual_concept:
            "Dynamic video showcasing product features in action.",
          copy_angle:
            "Highlighting the best of both worlds: style and performance.",
          hashtag_strategy: ["#PUMA", "#SneakerStyle"],
          viral_triggers: ["Aspirational empowerment"],
        },
        strategic_context: {
          week_focus: "Kickstart Your Fitness Journey",
          psychological_principle: "Aspirational empowerment",
          expected_engagement: "High views and comments",
          success_metrics: ["View Counts", "Engagement Rates"],
          optimization_notes: "Promote through social media channels.",
        },
        production_requirements: {
          effort_level: "HIGH",
          resources_needed: ["Videographer", "Product team"],
          preparation_time: "5 days",
          collaboration_needs: "Marketing team for promotion",
        },
    },
    {
        post_number: 4,
        date: "2025-09-25",
        day_of_week: "Thursday",
        week_number: 1,
        platform: "Instagram",
        content_pillar: "Entertainment",
        funnel_stage: "AWARENESS",
        content_concept: {
          concept_id: "ENT_001",
          title: "Fun Fitness Memes",
          description: "Create entertaining memes around fitness and fashion.",
          hook: "Laughter is the best motivation!",
          value_proposition: "Use humor to connect with the community.",
          call_to_action: "Tag a friend who needs a laugh!",
          engagement_tactics: ["Share your favorite fitness jokes"],
        },
        creative_elements: {
          format: "POST",
          visual_concept:
            "Funny visuals that resonate with the fitness community.",
          copy_angle: "Humor in fitness keeps you motivated.",
          hashtag_strategy: ["#FitnessHumor", "#PUMAMemes"],
          viral_triggers: ["Shareability of meme content"],
        },
        strategic_context: {
          week_focus: "Kickstart Your Fitness Journey",
          psychological_principle: "Joy and entertainment",
          expected_engagement: "High shares and comments",
          success_metrics: ["Share Rates", "Engagement Rates"],
          optimization_notes: "Monitor trending topics for relevance.",
        },
        production_requirements: {
          effort_level: "LOW",
          resources_needed: ["Graphic designer"],
          preparation_time: "1 day",
          collaboration_needs: "Social media team for insights",
        },
    },
    {
        post_number: 5,
        date: "2025-09-26",
        day_of_week: "Friday",
        week_number: 1,
        platform: "Facebook",
        content_pillar: "Community",
        funnel_stage: "RECALL",
        content_concept: {
          concept_id: "COM_001",
          title: "PUMA Community Challenge",
          description:
            "Encourage followers to participate in a fitness challenge using PUMA products.",
          hook: "Join the challenge and win prizes!",
          value_proposition: "Community spirit and engagement.",
          call_to_action: "Share your progress with #PUMAChallenge!",
          engagement_tactics: ["Encourage comments on challenge progress"],
        },
        creative_elements: {
          format: "POST",
          visual_concept: "Engaging visuals promoting the challenge.",
          copy_angle: "Unite through fitness and fashion.",
          hashtag_strategy: ["#PUMAChallenge", "#CommunityFitness"],
          viral_triggers: ["Community connection"],
        },
        strategic_context: {
          week_focus: "Kickstart Your Fitness Journey",
          psychological_principle: "Community connection",
          expected_engagement: "High participation and shares",
          success_metrics: ["User Engagement", "Challenge Entries"],
          optimization_notes: "Highlight participants' stories weekly.",
        },
        production_requirements: {
          effort_level: "MEDIUM",
          resources_needed: ["Graphic designer", "Community manager"],
          preparation_time: "2 days",
          collaboration_needs: "Marketing team for promotions",
        },
    },
    {
        post_number: 6,
        date: "2025-09-29",
        day_of_week: "Monday",
        week_number: 2,
        platform: "Instagram",
        content_pillar: "Inspirational",
        funnel_stage: "RECALL",
        content_concept: {
          concept_id: "INS_001",
          title: "Real Users, Real Stories",
          description:
            "Feature real customers sharing their transformation stories.",
          hook: "Real stories from real people can inspire you!",
          value_proposition: "Empowerment through community.",
          call_to_action: "Share your story with us!",
          engagement_tactics: ["Encourage users to share their stories"],
        },
        creative_elements: {
          format: "REEL",
          visual_concept: "Video snippets of customer stories.",
          copy_angle: "Inspiration from our community.",
          hashtag_strategy: ["#PUMARelationships", "#Transformation"],
          viral_triggers: ["Social proof"],
        },
        strategic_context: {
          week_focus: "Community Connection",
          psychological_principle: "Empowerment through community",
          expected_engagement: "High shares and comments",
          success_metrics: ["User-Generated Content", "Engagement Rates"],
          optimization_notes: "Highlight different stories weekly.",
        },
        production_requirements: {
          effort_level: "LOW",
          resources_needed: ["Content creator", "Video editor"],
          preparation_time: "1 day",
          collaboration_needs: "Community manager for story collection",
        },
    },
  ],
};
